server.port=9000

spring.application.name=auth-server

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.security.oauth2.authorizationserver.issuer=http://localhost:9000

spring.security.oauth2.authorizationserver.client.backend-client.registration.client-id=backend-client
spring.security.oauth2.authorizationserver.client.backend-client.registration.client-secret={noop}backend3-secret
spring.security.oauth2.authorizationserver.client.backend-client.registration.client-authentication-methods[0]=client_secret_basic
spring.security.oauth2.authorizationserver.client.backend-client.registration.authorization-grant-types[0]=client_credentials
spring.security.oauth2.authorizationserver.client.backend-client.registration.scopes[0]=transferencias.read
spring.security.oauth2.authorizationserver.client.backend-client.registration.scopes[1]=transferencias.write